---

# ansible-playbook -b -i osmc.lan, -k -u osmc main.yml

- hosts: all

  vars_prompt:
    - name: new_password
      prompt: NEW password
      confirm: yes

  roles:
    - role: geerlingguy.docker
      vars:
        docker_apt_ansible_distribution: "{{ ansible_os_family }}"
        docker_install_compose_plugin: no
        docker_packages:
          - docker-{{ docker_edition }}:arm64
          - docker-{{ docker_edition }}-cli:arm64
          - containerd.io:arm64
        docker_users:
          - osmc

  tasks:
    - ansible.builtin.apt:
        name:
          - hd-idle
          - resolvconf
          - rsync
          - wireguard-tools

    - ansible.builtin.cron:
        name: "{{ item.name }}"
        job: "{{ item.job }}"
        hour: "{{ item.hour }}"
        minute: "0"
        weekday: "1-5"
        user: osmc
      loop:
        - name: Transmission start
          job: /home/osmc/Transmission/start.sh
          hour: "17"
        - name: Transmission stop
          job: /home/osmc/Transmission/stop.sh
          hour: "5"

    - ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: osmc
        group: osmc
      loop:
        - /home/osmc/Transmission
        - /home/osmc/Youtube

    - ansible.builtin.copy:
        content: "{{ item.content }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
        owner: osmc
        group: osmc
      loop:
        - content: |
            #!/usr/bin/bash
            PATH=/usr/bin:/sbin
            set -e
            wg-quick up transmission
            docker container run -d -e PUID=1000 -e PGID=1000 -e TZ=Europe/Stockholm -e USER=osmc -e PASS={{ new_password | quote }} --name transmission -p 9091:9091 -p 51413:51413 -p 51413:51413/udp --pull always -v /home/osmc/Transmission/config:/config -v /home/osmc/Transmission/downloads:/downloads linuxserver/transmission:latest
          dest: /home/osmc/Transmission/start.sh
          mode: "555"
        - content: |
            #!/usr/bin/bash
            PATH=/usr/bin:/sbin
            set -e
            docker container rm -f transmission
            wg-quick down transmission
          dest: /home/osmc/Transmission/stop.sh
          mode: "555"
        - content: |
            FROM alpine:latest
            RUN apk add --no-cache ffmpeg python3 && \
                wget -P /usr/local/bin https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp && \
                chmod +x /usr/local/bin/yt-dlp
            USER 1000:1000
            WORKDIR /data
            ENTRYPOINT ["yt-dlp"]
          dest: /home/osmc/.dockerfile.yt-dlp
          mode: "444"

    - ansible.builtin.lineinfile:
        path: "{{ item.path }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backrefs: "{{ item.backrefs | default(omit) }}"
      loop:
        - path: /etc/default/hd-idle
          regexp: ^#?HD_IDLE_OPTS=
          line: HD_IDLE_OPTS="-i 0 -a /dev/sda -i 600 -l /var/log/hd-idle.log"
        - path: /home/osmc/.bashrc
          regexp: ^#?alias ll=(.*)
          line: alias ll=\1
          backrefs: yes
        - path: /home/osmc/.bashrc
          regexp: ^#?export LC_ALL=
          line: export LC_ALL=C.UTF-8
        - path: /home/osmc/.bashrc
          regexp: ^#?yt-dlp()
          line: yt-dlp() { docker build --pull -t localhost/yt-dlp - < /home/osmc/.dockerfile.yt-dlp && docker run --rm -v /home/osmc/Youtube:/data localhost/yt-dlp -f "bv*[height<=${2:-1080}][protocol^=http][vcodec^=avc]+ba[ext=m4a]" "${1}"; }

    - ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      loop:
        - path: /etc/ld.so.preload
          regexp: '^(\/usr\/lib\/libarmmem\.so)$'
          replace: '#\1'
        - path: /home/osmc/.bash_logout
          regexp: '^(\s*)(\[\s+-x\s+\/usr\/bin\/clear_console\s.*)$'
          replace: '\1: # \2'

    - ansible.builtin.raw: echo -e "{{ ansible_password }}\n{{ new_password }}\n{{ new_password }}" | passwd
      become_user: osmc
