---

- ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "755"
  become: "{{ item.become | default(omit) }}"
  loop:
    - url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
      dest: /usr/local/bin/docker-compose
      become: yes
    - url: https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
      dest: /usr/local/bin/minikube
      become: yes
    - url: https://dl.k8s.io/release/{{ lookup('ansible.builtin.url', 'https://dl.k8s.io/release/stable.txt') }}/bin/linux/amd64/kubectl
      dest: /usr/local/bin/kubectl
      become: yes
    - url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      dest: /tmp/get_helm.sh

- ansible.builtin.command:
    cmd: /tmp/get_helm.sh
    creates: /usr/local/bin/helm
  become: yes

- ansible.builtin.lineinfile:
    path: "{{ ansible_facts['env']['HOME'] }}/.bashrc"
    regexp: ^export DOCKER_HOST=
    line: export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock

- ansible.builtin.systemd_service:
    name: podman.socket
    enabled: yes
    scope: user

- ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    append: yes
    groups: libvirt
  become: yes
