---

- community.general.ini_file:
    path: "{{ item.path }}"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    create: no
    no_extra_spaces: yes
  become: yes
  loop:
    - path: /etc/fwupd/remotes.d/lvfs.conf
      section: fwupd Remote
      option: Enabled
      value: false
    - path: /etc/yum.repos.d/google-chrome.repo
      section: google-chrome
      option: enabled
      value: 1

- ansible.builtin.copy:
    content: |
      [mullvad-stable]
      name=Mullvad VPN
      baseurl=https://repository.mullvad.net/rpm/stable/$basearch
      type=rpm
      enabled=1
      gpgcheck=1
      gpgkey=https://repository.mullvad.net/rpm/mullvad-keyring.asc
    dest: /etc/yum.repos.d/mullvad.repo
  become: yes

- ansible.builtin.dnf:
    name: "{{ item.name }}"
    allowerasing: "{{ item.allowerasing | default(omit) }}"
    disable_gpg_check: "{{ item.disable_gpg_check | default(omit) }}"
  become: yes
  loop:
    - name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm
      disable_gpg_check: yes
    - name: ffmpeg
      allowerasing: yes
    - name: google-chrome-stable
    - name: mullvad-vpn
    - name: python3-psutil
    - name: vim-enhanced
    - name: vlc
